# Generated by Django 4.2.4 on 2023-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='vendor_license',
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_license',
            field=models.ImageField(blank=True, null=True, upload_to='merchant/license'),
        ),
    ]
