# Generated by Django 4.2.4 on 2023-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_remove_merchant_vendor_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_license',
            field=models.ImageField(null=True, upload_to='merchant/license'),
        ),
    ]
