# Generated by Django 4.2.4 on 2023-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_merchant_merchant_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
